version: "3"
services:
  node:
    image: node:13.12.0-stretch
    ports:
      - '8080:3000'
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: /bin/sh -c "yarn install --dev && yarn run dev"
